name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: imfuzail/guestbook-go:latest
        
      - name: Check commit message and build image conditionally
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
          if [[ ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == 'true' }} || $COMMIT_MESSAGE =~ "BUILD_CONTAINER_IMAGE" ]]; then
            echo "Building Docker image"
          else
            echo "Skipping Docker image build"
            exit 0
          fi

