name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check PR merge or commit message
        id: check-condition
        run: |
          if [[ ${{ github.event_name }} == 'push' ]]; then
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              echo "::set-output name=condition::true"
            else
              echo "::set-output name=condition::false"
            fi
          elif [[ ${{ github.event_name }} == 'pull_request' && ${{ github.event.action }} == 'closed' && ${{ github.event.pull_request.merged }} == 'true' ]]; then
            echo "::set-output name=condition::true"
          elif [[ ${{ github.event_name }} == 'push' && $(git log -1 --pretty=%B) == *'BUILD_CONTAINER_IMAGE'* ]]; then
            echo "::set-output name=condition::true"
          else
            echo "::set-output name=condition::false"
          fi
        shell: bash

      - name: Login to Docker Hub
        if: steps.check-condition.outputs.condition == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        if: steps.check-condition.outputs.condition == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: imfuzail/guestbook-go:latest
